"""
Unit tests cho clarity_checker.py
Dùng pytest.
clarity_checker phải export một callable:
    check_clarity(question: str) -> {"is_clear": bool, "score": float, "issues": list[str]}
"""
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest
from clarity_checker import check_clarity


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _check(question: str) -> dict:
    result = check_clarity(question)
    assert "is_clear" in result, "Thiếu key 'is_clear'"
    assert "score" in result, "Thiếu key 'score'"
    assert "issues" in result, "Thiếu key 'issues'"
    assert isinstance(result["score"], (int, float)), "score phải là số"
    assert 0.0 <= result["score"] <= 1.0, "score phải trong [0, 1]"
    return result


# ---------------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------------

class TestClearQuestion:
    QUESTION = (
        "List the names and salaries of all employees "
        "who work in the Engineering department, ordered by salary descending."
    )

    def test_is_clear_true(self):
        result = _check(self.QUESTION)
        assert result["is_clear"] is True

    def test_score_above_threshold(self):
        result = _check(self.QUESTION)
        assert result["score"] >= 0.75

    def test_no_critical_issues(self):
        result = _check(self.QUESTION)
        # Câu rõ ràng không nên có issue nghiêm trọng
        critical_keywords = {"too short", "no action", "vague", "missing"}
        issues_lower = {i.lower() for i in result["issues"]}
        overlap = critical_keywords & issues_lower
        assert len(overlap) == 0, f"Câu rõ ràng không nên có issues: {overlap}"


class TestTooShort:
    QUESTION = "Find it"

    def test_is_clear_false(self):
        result = _check(self.QUESTION)
        assert result["is_clear"] is False

    def test_issues_contain_too_short(self):
        result = _check(self.QUESTION)
        issues_combined = " ".join(result["issues"]).lower()
        assert "too short" in issues_combined or "short" in issues_combined, (
            f"Expected 'too short' in issues, got: {result['issues']}"
        )

    def test_score_below_threshold(self):
        result = _check(self.QUESTION)
        assert result["score"] < 0.75


class TestNoActionWord:
    QUESTION = "Employees with salary"

    def test_is_clear_false_or_has_action_issue(self):
        result = _check(self.QUESTION)
        # Câu thiếu action word phải là không rõ ràng HOẶC có issue về action
        issues_combined = " ".join(result["issues"]).lower()
        has_action_issue = (
            "action" in issues_combined
            or "verb" in issues_combined
            or "select" in issues_combined
            or "list" in issues_combined
            or "find" in issues_combined
        )
        assert result["is_clear"] is False or has_action_issue, (
            f"Câu thiếu action word nên is_clear=False hoặc có issue về action. "
            f"Got: is_clear={result['is_clear']}, issues={result['issues']}"
        )

    def test_score_penalized(self):
        result = _check(self.QUESTION)
        assert result["score"] < 0.9, (
            "Câu thiếu action word nên bị trừ điểm"
        )


class TestGoodScore:
    QUESTION = (
        "Find the total revenue generated by each product category "
        "in the last quarter, and return only categories with revenue above 10000."
    )

    def test_perfect_score(self):
        result = _check(self.QUESTION)
        assert result["score"] == 1.0, (
            f"Câu đầy đủ nên đạt score=1.0, got {result['score']}"
        )

    def test_is_clear_true(self):
        result = _check(self.QUESTION)
        assert result["is_clear"] is True

    def test_issues_empty(self):
        result = _check(self.QUESTION)
        assert result["issues"] == [], f"Không nên có issues: {result['issues']}"


class TestEdgeCases:
    def test_empty_string(self):
        result = _check("")
        assert result["is_clear"] is False
        assert result["score"] == 0.0

    def test_whitespace_only(self):
        result = _check("   ")
        assert result["is_clear"] is False

    def test_score_type_is_float(self):
        result = _check("Select all employees.")
        assert isinstance(result["score"], float)
